spring.application.name=6.Link-Two-Collections
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=LinkTwoCollectionsDb
spring.data.mongodb.auto-index-creation=true
