spring.application.name=Audio-To-Text-Converter
spring.ai.openai.api-key=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
spring.ai.openai.audio.transcription.base-url=https://api.openai.com
spring.ai.openai.audio.transcription.options.model=whisper-1
spring.ai.openai.audio.transcription.options.response-format=json
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB