spring.data.mongodb.uri=mongodb+srv://ckray5503_db_user:R4aIHCn7wkk5sssE@cluster0.yo5u3fs.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=AtlasDbConnection
spring.data.mongodb.auto-index-creation=true
#ckray5503_db_user
#R4aIHCn7wkk5sssE
#Your current IP address (42.107.167.253)